export const data = [
    {
      question: "Which country does Forrest Gump travel to as part of the All-American Ping-Pong Team?",
      option1: "China",
      option2: "Vietnam",
      option3: "Sweden",
      option4: "France",
      ans: 1,
    },
    {
      question: " Freddy Krueger wears a striped sweater that is which colors?",
      option1: "Red and blue",
      option2: "Orange and green",
      option3: "Red and green",
      option4: "Orange and brown",
      ans: 3,
    },
    {
      question: "What was the top-grossing movie of 2014?",
      option1: "The Hunger Games: Mockingjay Part 1",
      option2: "The Lego Movie",
      option3: "Captain America: The Winter Soldier",
      option4: "Guardians of the Galaxy",
      ans: 4,
    },
    {
      question: "If you watch the Marvel movies in chronological order, which movie would you watch first?",
      option1: "Iron Man",
      option2: "Captain America: The First Avenger",
      option3: "Doctor Strange",
      option4: "Captain Marvel",
      ans: 2,
    },
    {
      question: "Raiders of the Lost Ark: What job does Indiana Jones do?",
      option1: "Tutor",
      option2: "Archaeology",
      option3: "Painter",
      option4: "SMM",
      ans: 2,
    },
    {
        question: "In The Ring, how long do people have to live after they watch a cursed videotape?",
        option1: "3 days",
        option2: "5 days",
        option3: "6 days",
        option4: "7 days",
        ans: 4,
    },
    {
        question: "What is the highest-grossing movie of all time?",
        option1: "Titanic ",
        option2: "Avatar ",
        option3: "Avengers: Endgame",
        option4: "Star Wars: The Force Awakens",
        ans: 2,
    },
    {
        question: "Which comedian makes a zombie cameo in Zombieland?",
        option1: "Dan Aykroyd",
        option2: "Chevy Chase",
        option3: "Steve Martin",
        option4: "Bill Murray",
        ans: 4,
    },
    {
        question: "In Black Panther, Wakanda is so technologically advanced because of which type of metal?",
        option1: "Vibranium",
        option2: "Titanium",
        option3: "Gold",
        option4: "Silverium",
        ans: 1,
    },
    {
        question: "In Zootopia, what type of animal is Judy Hopps?",
        option1: "Sloth",
        option2: "Fox",
        option3: "Rabbit",
        option4: "Ant",
        ans: 3,
    },
    {
        question: "Toy Story: What is the name of Andy's mean neighbour?",
        option1: "Johnny",
        option2: "Sid",
        option3: "Steve",
        option4: "Paul",
        ans: 2,
    },
    {
        question: "Which object is stuck in Puss in Boots' hat?",
        option1: "Pencil",
        option2: "Sandwich",
        option3: "Ribbon",
        option4: "Sword",
        ans: 1,
    },
    {
        question: "Mary Poppins Returns: How many children does Mary Poppins look after?",
        option1: "1",
        option2: "2",
        option3: "3",
        option4: "4",
        ans: 3,
    },
    {
        question: "Coco: What is Miguel's canine companion called?",
        option1: "Rover",
        option2: "Fang",
        option3: "Jeff",
        option4: "Dante",
        ans: 4,
    },
    {
        question: "Back to the Future: To which year does Marty McFly travel back in time?",
        option1: "1938",
        option2: "1955",
        option3: "1976",
        option4: "1984",
        ans: 2,
    },
  ];